<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;


/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function getAllAdverts()
    {
        $qb = $this->createQueryBuilder('a')
            ->select(['a', 'address', 'category', 'project', 'user'])
            ->innerJoin('a.address', 'address')
            ->innerJoin('a.category', 'category')
            ->innerJoin('a.project', 'project')
            ->innerJoin('a.user', 'user')
            ->getQuery();

        $query = $qb->getResult();
        return $query;
    }

    /**
     * @param User $user
     * @return array
     */
    public function getAdvertsByUser(User $user)
    {
        $qb = $this->createQueryBuilder('a')
            ->select(['a'])
            ->where('a.user = :user');
        $query = $qb->getQuery()
            ->setParameter('user', $user->getId());

        return $query->getResult();
    }
}
