# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        user_provider:
            entity:
                class: AppBundle:User
                property: email
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\User:
            algorithm: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        author:
            pattern: ^/user
            anonymous: false
            provider: user_provider
            form_login:
                login_path: login_user
                check_path: login_user_check
                default_target_path: /user
            logout:
                path: logout_user
                target: advert_index

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
